name: ci-artifacts

on:
  push:

env:
  LC_CTYPE: C.UTF-8

jobs:
  minimal-sdk-artifact:
    runs-on: windows-latest
    steps:
      - name: clone git-sdk-64
        shell: bash
        run: git clone --bare --depth=1 --filter=blob:none --single-branch -b ${REF#refs/heads/} https://github.com/${{github.repository}}
        env:
          REF: ${{github.ref}}
      - name: clone build-extra
        run: git clone --depth=1 --single-branch -b main https://github.com/git-for-windows/build-extra
      - name: build git-sdk-64-minimal-sdk
        shell: bash
        run: sh -x ./build-extra/please.sh create-sdk-artifact --sdk=git-sdk-64.git minimal-sdk
      - name: replace msys2-runtime
        shell: bash
        run: |
          curl  -Lo /tmp/msys2-runtime.zip \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
            https://api.github.com/repos/dscho/msys2-runtime/actions/artifacts/352801589/zip &&
          unzip -v /tmp/msys2-runtime.zip &&
          unzip -p /tmp/msys2-runtime.zip usr/bin/msys-2.0.dll >minimal-sdk/usr/bin/msys-2.0.dll
      - name: compress artifact
        shell: bash
        run: (cd minimal-sdk && tar cvf - * .[0-9A-Za-z]*) | xz -9 >git-sdk-64-minimal.tar.xz
      - name: upload minimal-sdk artifact
        uses: actions/upload-artifact@v1
        with:
          name: minimal-sdk
          path: git-sdk-64-minimal.tar.xz
  test-minimal-sdk:
    runs-on: windows-latest
    needs: [minimal-sdk-artifact]
    steps:
      - name: download minimal-sdk artifact
        uses: actions/download-artifact@v1
        with:
          name: minimal-sdk
          path: ${{github.workspace}}
      - name: uncompress minimal-sdk
        shell: bash
        run: mkdir -p minimal-sdk && tar -C minimal-sdk -xJf git-sdk-64-minimal.tar.xz
      - name: test
        run: |
          & .\minimal-sdk\usr\bin\bash.exe -lc @"
            uname -a
          "@
