name: git-artifacts

on:
  push:
    branches:

env:
  REPOSITORY: git-for-windows/git
  REF: main

  GIT_CONFIG_PARAMETERS: "'checkout.workers=56'"
  HOME: "${{github.workspace}}\\home"
  USERPROFILE: "${{github.workspace}}\\home"
  MSYSTEM: MINGW64

  ARCH_NAME: x86_64
  ARCH_BITNESS: 64

jobs:
  artifacts:
    runs-on: windows-latest
    strategy:
      matrix:
        artifact: [installer]
      fail-fast: false
    steps:
      - name: reuse artifact
        shell: bash
        run: |
          run_id=3964412678 &&
          name=installer-x86_64 &&

          curl -L https://api.github.com/repos/git-for-windows/git-sdk-64/actions/runs/$run_id/artifacts |
          jq -r '.artifacts[] | select(.name | test("'$name'")) | [.name, .archive_download_url] | @tsv' |
          tr -d '\r' |
          while read name url
          do
            echo "$name"
            curl -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
              -#sLo /tmp/"$name".zip "$url" &&
            mkdir "$name" &&
            unzip -q -d "$name" /tmp/"$name".zip
          done

      - name: Run the installer
        if: matrix.artifact == 'installer'
        shell: pwsh
        run: |
          $exePath = Get-ChildItem -Path installer-x86_64/*.exe | %{$_.FullName}
          Start-Process -Wait -FilePath "$exePath" -ArgumentList "/SILENT /VERYSILENT /NORESTART /SUPPRESSMSGBOXES /ALLOWDOWNGRADE=1 /LOG=installer.log"
          "$env:ProgramFiles\Git\usr\bin" | Out-File -Encoding ascii -Append $env:GITHUB_PATH
          "$env:ProgramFiles\Git\mingw${{env.ARCH_BITNESS}}\bin" | Out-File -Encoding ascii -Append $env:GITHUB_PATH
      - name: Validate
        if: matrix.artifact == 'installer'
        shell: bash
        run: |
          set -x &&
          cygpath -aw / &&
          git.exe version --build-options >version &&
          cat version &&
          grep "$(sed -e 's|^v||' -e 's|-|.|g' <bundle-artifacts/next_version)" version &&
          checklist=build-installers/usr/src/build-extra/installer/run-checklist.sh &&
          # cannot test SSH keys in read-only mode, skip test for now
          sed -i 's|git@ssh.dev.azure.com:v3/git-for-windows/git/git|https://github.com/git/git|' $checklist &&
          sh -x $checklist
      - name: action-tmate
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
